config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :detail, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    if (params[:post][:post_type] == "single")
      upload_single_file(params[:post][:detail])
    elsif params[:post][:post_type] == "multiple"
      upload_multiple_file(params[:post][:detail])
    elsif params[:post][:post_type] == "mp4"
      upload_video_file(params[:post][:detail])
    end
    respond_to do |format|
      if @post.present?
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to new_post_path}
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    obj = S3_BUCKET.object(@post.detail)
    obj.delete && @post.destroy 
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :detail)
    end
    
    def upload_single_file(file_details)
      if file_details.content_type == "image/jpeg"
        upload_file(file_details)
      end
    end
    
    def upload_multiple_file(file_details)
      if (file_details.count > 1)
        file_details.each do |data|
          upload_file(data)
        end
      end
    end
    
    def upload_video_file(file_details)
      if file_details.content_type == "video/mp4"
         upload_file(file_details)
      end
    end
    
    def upload_file(file_payload)
      obj = S3_BUCKET.object(file_payload.original_filename)
      obj.put(body: file_payload.to_io)
      @post = Post.create(title: obj.public_url, detail: obj.key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UploadApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= form.hidden_field :post_type, :value => "single" %>
  <div class="field">
    <%=label_tag 'upload only single JPEG file'%>
  </div>
  <div class="field">
    <%= form.file_field :detail%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= form_with(model: post, local: true) do |form| %>
  <%= form.hidden_field :post_type, :value => "multiple" %>
  <div class="field">
    <%=label_tag 'upload multiple files'%>
  </div>
  <div class="field">
    <%= form.file_field :detail, :multiple => true %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= form_with(model: post, local: true) do |form| %>
  <div class="field">
    <%=label_tag 'upload only MP4 files'%>
  </div>
  <%= form.hidden_field :post_type, :value => "mp4" %>
  <div class="field">
    <%= form.file_field :detail%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.detail %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
  <%= image_tag(@post.title, width: 200) if @post.title.present? %>

<p>
  <strong>Detail:</strong>
  <%= @post.detail %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>